export const responseMessages = {
  EN: {
    'ACCOUNT_DISABLED': 'Your account is disabled please contact to admin',
    'POST_NOTFOUND': 'Post not found',
    'ALREADY_EXIST': 'Aleardy Exist Please Login',
    'ALREADY_REGISTER': 'Email already registered',
    'POST_ADDED': 'Post added successfully',
    'REQUEST_ADDED': 'Your request has been successfully sent',
    'MESSAGE_ADDED': 'Message added successfully',
    'BAD_REQUEST': 'Bad request',
    'CREATE': 'Created successfully',
    'DELETE_POST': 'Post deleted successfully',
    'DELETE_CATEGORY': 'Category deleted successfully',
    'DELETE_USER': 'User deleted successfully',
    'DELETE_NOTIFICATIONS': 'Notifications deleted successfully',
    'EMAIL_NOT_REGISTER': 'Email not registered',
    'ERROR': 'Something went wrong',
    'FETCH_POST': 'Fetch post successfully',
    'END_POST': 'Post ended successfully',
    'FETCH_CATEGORIES': 'Fetch categories successfully',
    'FETCH_POSTS': 'Fetch posts successfully',
    'FETCH_REQUEST': 'Fetch request successfully',
    'FETCH_QR_CODE': 'Fetch QRcode successfully',
    'FETCH_SETTING': 'Fetch setting successfully',
    'FETCH_CONTACT': 'Fetch contact successfully',
    'DELETE_CHAT': 'Chat Deleted successfully',
    'FETCH_USER': 'Fetch user successfully',
    'FETCH_WEEK_USER': 'Fetch this week users successfully',
    'FETCH_CATEGORIES': 'Fetch categories successfully',
    'FETCH_ADMIN': 'Fetch admin successfully',
    'FETCH_USERS': 'Fetch users successfully',
    'FETCH_NOTIFICATIONS': 'Fetch notifications successfully',
    'FETCH_REFRESH_TOKEN': 'Fetch refresh token successfully',
    'FORBIDDEN': 'Forbidden',
    'INVALID': 'Invalid email or password',
    'INVALID_EMAIL': 'Invalid email',
    'PASSWORD_INVALID': 'Invalid password',
    'INVALID_PASSWORD': 'Invalid old password',
    'LOGIN': 'Login successfully',
    'LOGOUT': 'Logout successfully',
    'NOTIFICATION_SEND': 'Notification sent successfully',
    'OTP_FOR_PASSWORD': 'OTP For Password Reset Sent To Your Email',
    'OTP_MISMATCH': 'OTP mismatched',
    'OTP_SENT': 'OTP sent in your registered email',
    'PASSWORD_CHANGED': 'Password Changed Successfully',
    'POST_UPDATE': 'Post updated successfully',
    'UPDATE_REQUEST_STATUS': 'Request status updated successfully',
    'REQUEST_UNSEND': 'Request Unsend successfully',
    'REQUEST_CANCELLED': 'Request Cancelled Successfully',
    'UPDATE_CATEGORY': 'Category updated successfully',
    'RESET_PASSWORD': 'Password Reset Successfully',
    'REQUEST_FORBIDDEN': 'Request is forbidden',
    'SELECT_IMAGE': 'Please select an image to upload',
    'SESSION_EXPIRED': 'Session expired, please login again',
    'STATUS_UPDATE': 'Status updated successfully',
    'SUCCESS': 'Success',
    'SUFFICIENT_RIGHTS': 'You do not have sufficient rights',
    'UNAUTHORIZED': 'Unauthorized',
    'UPDATE_SETTING': 'Settings updated successfully',
    'UPDATE_STATUS': 'Status updated successfully',
    'UPDATE_USER': 'Profile updated successfully',
    //'UPDATE_USER': 'Changes Done successfully',
    'UPDATE_POST': 'Post Updated Successfully',
    'UPDATE_GROUP': 'Group Updated Successfully',
    'REMOVE_GROUP_PARTICPANTS': 'Remove Group Member Successfully',
    'USER_ADDED': 'User registered successfully',
    'USER_NOTFOUND': 'User not found',
    'VALID': 'Valid',
    'VERIFY_OTP': 'OTP Verified',
    'POST_CANCEL': 'Event cancelled',
    'REQUEST_ALREADY_SENT': 'Request already sent',
    'REQUEST_IN_OWN_POST': 'You Can Not Sent Request In Your Own Post',
    'GROUP_FULL': 'Group Is Already Full',
    'NOTIFICATION_TURN_OFF': 'Notification turned off',
    'REPORT_POST': 'Post reported successfuly',
    'REPORT_USER': 'User reported successfuly',
    'CHAT_FETCH': 'Chat Record fetched successfully',
    'UPDATE_ICON': 'Updated Group icon successfully',
    'GROUP_DETAILS': 'Group Details fetched successfully',
    'PERSONAL_MESSAGE': 'Personal Message fetched successfully',
    'REQUEST_NOT_FOUND': 'Request not found',
    'REFRESH_TOKEN': 'Token refresh successfully',
    'ADMIN_ADDED': 'Admin added successfully',
    'PASSWORD_REQUIRED': 'Password is required',
    'ALREADY_REPORT': 'Already Reported',
    'ADDED_CATEGORIES': 'Categories added successfully',
    'QUERY_SENT': 'Query sent successfully',
    'NOT_VERIFIED': 'Account not verified',
    'SOCIAL_LOGIN': 'Please login with social account',
    'NOTIFICATION_UPDATED': 'Notification updated success',
    'GROUP_NOT_FOUND': 'Group not found',
    'NOT_MEMBER': 'Not a member of group',
    'GROUP_ADMIN': 'Admin cannot exit.Please delete the group.',
    'GROUP_ADMIN_DELETE': 'Only Admin can delete group.',
    'BLOCK_USER': 'User Blocked successfully.',
    'LOTTERY_ADDED': 'Lottery added success',
    'UPDATE_LOTTERY': 'Lottery Updated',
    'LOTTERY_FETCHED': 'Lottery fetched'
  },
  'FR': {

  }
}

export const notificationPayload = {}

export const statusCodes = {
  'SUCCESS': 200,
  'RECORD_CREATED': 201,
  'BAD_REQUEST': 400,
  'AUTH_ERROR': 401,
  'FORBIDDEN': 403,
  'NOT_FOUND': 404,
  'INVALID_REQUEST': 405,
  'RECORD_ALREADY_EXISTS': 409,
  'SERVER_ERROR': 500
}

const makeResponse = async (res, statusCode, success, message, payload = null, meta = {}) =>
  new Promise(resolve => {
    res.status(statusCode)
      .send({
        success,
        code: statusCode,
        message,
        data: payload,
        meta
      });
    resolve(statusCode);
  });

export { makeResponse };
